# Generated by Django 5.1.6 on 2025-03-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSocketApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='room',
            new_name='name',
        ),
    ]
